<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="FB_Sequencer" Id="{082739e2-22b9-4029-95b6-33dd5a220750}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Sequencer
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_Sequencer">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>