<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="PRG_StationPLC" Id="{4d44d755-1020-0291-3db4-9567f2cbe7cf}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_StationPLC
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[M_Handshake();]]></ST>
    </Implementation>
    <Method Name="M_Handshake" Id="{f4147963-58c3-0020-15d8-89f48fc39b27}">
      <Declaration><![CDATA[METHOD M_Handshake
VAR_INPUT
END_VAR
VAR
	fbStationPLC : FB_StationPLC;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[// Here is to bind Leak Test run cmd from the station Control PLC
// the cmd then will run the PRG_LeakTest
// fbStationPLC();  Call when its coded]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>