<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_MainPLC" Id="{c2bbdccd-edf6-4203-96ae-745c9a753c49}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_MainPLC IMPLEMENTS I_Device
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="CmdLeakTestStart" Id="{cfa4305f-0c87-4da6-8add-9de9e2c6cc35}">
      <Declaration><![CDATA[METHOD CmdLeakTestStart : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="CmdLeakTestStop" Id="{cfc40875-da1f-4dc1-bf11-4fd7f7fdfbe1}">
      <Declaration><![CDATA[METHOD CmdLeakTestStop : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="CommOK" Id="{4e264467-529a-414a-8c15-24209e4ea6ff}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD CommOK : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>