<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="PRG_TEST" Id="{17166b4e-59dc-4826-b23b-b13d729fc1f3}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_TEST
VAR

	fbAteqF6_IoMapper_Test : FB_Test_AteqF6_IoMapper;
	 
END_VAR


]]></Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.RUN();
fbAteqF6_IoMapper_Test();
]]></ST>
    </Implementation>
    <LineIds Name="PRG_TEST">
      <LineId Id="29" Count="0" />
      <LineId Id="22" Count="0" />
      <LineId Id="25" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>