<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="PRG_MAIN" Id="{075ea502-c30b-43b0-8467-21d133ac9e69}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_MAIN
VAR

	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//Update System time in every Task Cycle
GVL_System.nTime := Tc2_System.F_GetSystemTime();]]></ST>
    </Implementation>
    <LineIds Name="PRG_MAIN">
      <LineId Id="8" Count="0" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>