<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="PRG_TEST" Id="{17166b4e-59dc-4826-b23b-b13d729fc1f3}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_TEST
VAR
// Enable the test FBs to RUN TcUnit
	//fbTest_AteqControl	: FB_Test_AteqControl;
	//fbTest_ValveBank 		: FB_Test_ValveBank;

END_VAR


]]></Declaration>
    <Implementation>
      <ST><![CDATA[
	//TcUnit.RUN_IN_SEQUENCE();

]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>