<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_TextFile" Id="{a8fbbdb2-8622-4f28-96c1-2e6d5da1b20c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_TextFile
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Read" Id="{125b370c-fee2-4bc3-952c-f17051a924a3}">
      <Declaration><![CDATA[METHOD Read : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>